### ISSUE TITLE
How does it works

### ISSUE THREAD

**Issue by SatanicScripter** [Impulsx/GoS#1]
I have installed Gos launcher, but I don't know how to go on. How can I do?

**Comment by Impulsx** [comment]
GoS website where you hopefully downloaded the official exe is where you need to register/buy to sign in and use GoS.
The rest is pretty much on the forums for how to install/run/use scripts.


If all that's good, simple way is just to right click in the Scripts area and "install new script" which will as for RAW link.
![image](https://user-images.githubusercontent.com/17681540/170833745-f706180c-92ac-4ea5-8dbb-f76005c91620.png)
Example raw link to pussyAIO: https://raw.githubusercontent.com/Impulsx/GoS/master/PussyAIONewGen.lua
or go to https://github.com/Impulsx/GoS/blob/master/PussyAIONewGen.lua and click the RAW
![image](https://user-images.githubusercontent.com/17681540/170833822-31e8a0b9-40f5-4f64-ad21-18f866120eed.png)

**Comment by SatanicScripter** [comment]
And then? There are also champ script. What have I to do with them? @Impulsx

**Comment by SatanicScripter** [comment]
And also have I to buy external? Or can I use internal? @Impulsx
