### ISSUE TITLE
Other questions (sorry)

### ISSUE THREAD

**Issue by SatanicScripter** [Impulsx/GoS#2]
Sorry if I contact you again, but your response to my previous issue was not very comprehensive.
On its repo, there are also other scripts; here is a picture:
![image](https://user-images.githubusercontent.com/75582345/171621946-fdf9f262-2c0d-47a6-bb5d-3be76e32057e.png)

**What should I do with these?**

I also read in his reply that I had to buy something.
**Do I have to buy the external or can I stay with the internal?**

**Comment by Impulsx** [comment]
14Yasuo_Vol2 is pussy's edit of 14Yasuo, You can use it I don't know how it fairs vs. other yasuo scripts tho.
DamageLib is the Offical DamageLib for GoS I've been updating and can be ignored

**Comment by SatanicScripter** [comment]
So have I to buy Internal for the scripts? 
Thanks
